config/routes.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
require 'sidekiq/api'

Rails.application.routes.draw do
  namespace :admin do
    resources :terms_of_use, controller: :terms_of_use
    resources :users
    root to: "users#index"
  end

  root to: 'search#search'

  resources :request_accesses do
    member do
      post :approve
      post :reject
    end
  end

  resources :dataset_algorithms

  resources :update_activities


  # temporarily disabled by BDP-820
  get 'newsfeed' => 'newsfeed#index'
  get 'newsfeed/load_more'

  resources :datasources

  resources :like_activities

  resources :review_activities

  resources :share_activities

  resources :search_activities

  resources :view_activities

  resources :ingest_activities

  resources :contributors

  resources :columns

  resources :algorithms

  resources :user_elasticsearch_solutions

  get 'sessions/login', as: 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'auth/:provider/callback', to: 'sessions#create'
  #post 'sessions/login_attempt'
  get 'sessions/impersonate'
  get 'sessions/cancel_impersonation'

  resources :dataset_visual_tools

  resources :tags do
    collection do
      get :autocomplete
      get :popular
    end
  end

  resources :lineages do
    member do
      get :details
    end
  end

  resource :terms_of_use, controller: :terms_of_use, only: [:create] do
    member do
      get :accept
      get :actual
    end
  end

  resource :tables do
    resources :columns
  end

  resources :datasets, only: :show do
    # resources :transformations
    resources :attributes, controller: :dataset_attributes, except: [:index, :show], as: :dataset_attributes do
      collection do
        get :autocomplete
      end
    end

    resources :notes, only: [:edit, :create, :update, :destroy]

    resource :tables do
      resources :columns
    end

    member do
      get :like
      get :share
      get :explore_lineage
      get :lineage_dataset_details

      post :update_columns
      post :update_tags
      post :upload_metadata
      get :redisplay_columns

      post 'ask-for-request' => 'dataset/request_accesses#create'
      get 'connection_info' => 'dataset/connection_info#show',
          as: :connection_info

      namespace :dataset, path: '' do
        resources :request_accesses, only: [:index], param: :request_access_id do
          member do
            post :approve
            post :reject
          end
        end
      end
    end
  end

  resources :terms_of_services

  resources :subject_areas

  get 'search/search'
  get 'search/related_tags'
  get 'search/related_people'
  get 'search' => 'search#search', as: :search
  get 'search/autocomplete'

  get 'mydatasets' => 'users#mydatasets', as: :mydatasets

  resources :users

  resources :my_datasets, only: [:new, :create, :edit, :update, :destroy] do
    resource :transformation, only:  [:create, :edit, :update]
    member do
      get :check_on_status
      get :template_for_initial_scenario
    end
  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      post 'sessions' => 'sessions#create'
      jsonapi_resources :datasets
      jsonapi_resources :dataset_attributes
      jsonapi_resources :notes
      jsonapi_resources :tags
      jsonapi_resources :subject_areas
      jsonapi_resources :datasources
      jsonapi_resources :users do
        collection do
          post :verify
        end
      end
    end
  end

  # sidekiq
  mount Sidekiq::Web, :at => 'sidekiq', :constraints => SidekiqWebConstraint.new
  get "sidekiq/status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new.size < 10000 ? "OK" : "UHOH"]] }

  match '*path' => 'application#routing_error', via: :all
 # get ':controller/:action'
end

app/controllers/search_controller.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
class SearchController < ApplicationController
  RESULTS_PER_PAGE = 10

  DATASET_SEARCH_FIELDS = %w(
    name^10
    description^2
    owner.full_name^2
    subject_area.name
    country_code
    country_name
    datasources.name
    tags.name^2
    tables.name
    columns.name
    columns.business_name
    dataset_attributes.key
    dataset_attributes.value^3
    dataset_attributes.comment
  )

  def search
    @search_duration = 0

    # Expose the selected facets to the view, so they can remain checked.
    @selected_tags = (params['tags'] || []).map(&:to_i)
    @selected_owner = (params['owner'] || []).map(&:to_i)
    @selected_subject_area = (params['subject_area'] || []).map(&:to_i)
    @selected_country_codes = params['country_code']

    search_result = perform_search
    @search_duration += search_result.took
    @total_results = search_result.results.total

    aggregations_result = perform_aggregations_search
    @search_duration += aggregations_result.took

    @tags, @tags_count = build_facet(aggregations_result, :tags, Tag)
    @subject_areas, @subject_areas_count = build_facet(aggregations_result, :subject_area, SubjectArea)
    @owners, @owners_count = build_facet(aggregations_result, :owner, User)
    @countries, @countries_count = build_country_facet(aggregations_result, :country_code)

    @datasets = search_result.records
  rescue Exception
    @datasets = []
  end

  def autocomplete
    render json: fetch_suggestions, root: false
  end

  def related_tags
    aggregation = { tags: { terms: { field: :"tags.id" } } }
    build_related_search(aggregation, 'tags')
  end

  def related_people
    aggregation = { owner: { terms: { field: :"owner.id" } } }
    build_related_search(aggregation, 'owner')
  end

  private

  def query
    @query ||= params.fetch('query', '')
  end

  def perform_search
    payload = {
      query: {
        filtered: build_query_params
      },
      highlight: {
        pre_tags: ["<mark>"],
        post_tags: ["</mark>"],
        fields: {
          name: {},
          description: {number_of_fragments: 0}
        }
      }
    }
    logger.info("Search query:\n#{payload.to_json}")

    Dataset.search(payload).paginate(page: params[:page], per_page: RESULTS_PER_PAGE)
  end

  def perform_aggregations_search
    payload = {
      query: build_aggregation_query_params,
      aggs: dataset_aggregations
    }

    logger.info("Aggregations query:\n#{payload.to_json}")

    Dataset.search(payload)
  end

  def dataset_aggregations
    {
      tags: {
        terms: {
          field: "tags.id",
          size: 0
        }
      },
      subject_area: {
        terms: {
          field: "subject_area.id",
          size: 0
        }
      },
      owner: {
        terms: {
          field: "owner.id",
          size: 0
        }
      },
      country_code: {
        terms: {
          field: "country_code",
          size: 0
        }
      }
    }
  end

  def build_facet(aggregations_result, filter, model)
    entity_ids = []
    entities_count = {}

    aggregations_result.aggregations[filter]['buckets'].each do |bucket|
      entity_ids << bucket['key']
      entities_count[bucket['key'].to_i] = bucket['doc_count']
    end

    entities = model.find(entity_ids)
    entities.sort! { |a, b| entities_count[b.id] <=> entities_count[a.id] }

    [entities, entities_count]
  end

  def build_country_facet(aggregations_result, filter)
    entity_ids = []
    entities_count = {}

    aggregations_result.aggregations[filter]['buckets'].each do |bucket|
      entity_ids << bucket['key']
      entities_count[bucket['key']] = bucket['doc_count']
    end

    entities = Dataset.where(country_code: entity_ids.map(&:upcase)).uniq.pluck(:country_code).to_a
    entities.sort! { |a, b| entities_count[b] <=> entities_count[a] }

    [entities, entities_count]
  end

  # Builds the filtered query parameters for the main elastic search.
  # Will NOT include the "query" field if NO query was provided (ex. only filtering by 'tags')
  def build_query_params
    query_params = { filter: generate_filter(params) }
    query_params[:query] = dis_max_query if query.present?

    query_params
  end

  def build_aggregation_query_params
    query_params = {}

    if query.present?
      query_params[:dis_max] = dis_max_query[:dis_max]
    else
      query_params[:match_all] = {}
    end

    query_params
  end

  def dis_max_query
    dis_max = {
      dis_max: {
        tie_breaker: 0.3,
        queries:  [
          {
            bool: {
              should: [
                {
                  match_phrase: {
                    name: {
                      query: query,
                      slop: 50
                    }
                  }
                },
                {
                  match: {
                    'name.shingles': query
                  }
                },
                {
                  match: {
                    name: query
                  }
                },
                {
                  wildcard: { name: query }
                }
              ],
              boost: extract_boost(DATASET_SEARCH_FIELDS.first).last,
              minimum_should_match: "25%"
            }
          }
        ]
      }
    }
    DATASET_SEARCH_FIELDS[1..-1].each do |field|
      field_name, boost = extract_boost(field)
      logger.info "#{field_name} => #{boost} -> #{query}"
      logger.info "dis: #{dis_max.inspect}"
      dis_max[:dis_max][:queries] << {
        bool: {
          should: [
            {
              match_phrase: {
                "#{field_name}" => {
                  query: query,
                  slop: 50
                }
              }
            },
            {
              match: {
                "#{field_name}" => query
              }
            },
            {
              wildcard: { "#{field_name}" => query }
            }
          ],
          boost: boost,
          minimum_should_match: "33%"
        }
      }
    end

    dis_max[:dis_max][:queries] << {
      multi_match: {
        query: query,
        type: 'cross_fields',
        fields: ['name^2', 'description', 'dataset_attributes.value']
      }
    }

    dis_max
  end

  def extract_boost(field)
    field_parts = field.split('^')
    field_name = field_parts.first
    boost = field_parts.size == 2 ? field_parts.last : 1

    [field_name, boost]
  end

  def generate_filter(params, fields = %w(tags subject_area owner country_code))
    filters = []

    fields.each do |f|
      if params[f].present?
        filters << (f == 'country_code' ? { terms: { "#{f}" => params[f] } } : { terms: { "#{f}.id" => params[f] } })
      end
    end

    if filters.empty?
      return {}
    elsif filters.length == 1
      return filters.first
    else
      return { and: filters }
    end
  end

  def scale_tags_for_cloud(tags)
    min_font = 20
    max_font = 60

    counts = tags.collect { |t| t[:size] }

    min_count = counts.min
    max_count = counts.max

    ratio = 1
    ratio = (max_font - min_font) / (max_count - min_count) unless max_count - min_count == 0

    tags.each do |t|
      t[:size] = (t[:size] - min_count) * ratio + min_font
    end

    tags
  end

  def fetch_suggestions
    SearchService.autocomplete(
      query: params.fetch('q', ''),
      fields: %w(name owner_name tag)
    )
  end

  def build_related_search(agg, filter)
    raw_search_result = Dataset.search(query: {
                                         multi_match: {
                                           query: query,
                                           fields: DATASET_SEARCH_FIELDS
                                         }
                                       },
                                       aggs: agg
                                      )

    @search_duration = raw_search_result.took
    @total_results = raw_search_result.results.total

    @tags = []

    if raw_search_result.aggregations
      raw_search_result.aggregations[filter]['buckets'].each do |b|
        case filter
        when 'tags'
          @tags << { text: Tag.find(b['key']).name, size: b['doc_count'] }
        when 'owner'
          @tags << { text: User.find(b['key']).full_name, size: b['doc_count'] }
        end
      end
    end

    @tags = scale_tags_for_cloud(@tags)
  end
end

app/views/search/_filter_countries.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.filter-section-title
  | COUNTRY
- @countries ||= []
- @render_countries = SearchFilterDecorator.new(@countries) { |t| (@selected_country_codes || []).include?(t) }
.filter-countries
  - @render_countries.renderables.each do |t|
    div class="country-filter #{t.html_class}"
      input.filter_checkbox[value=t.item.to_s.upcase id="country_code_#{t.item}" name="country_code[]" type="checkbox" onclick="$('#search_filter').submit();" checked=t.checked]
      = label_tag nil, "#{find_by_country_code(t.item.to_s.upcase)} (#{@countries_count[t.item.to_s.upcase]})", for: "country_code_#{t.item}"
- if @render_countries.show_more?
  a.toggle-all-countries[onclick="filterOverflowToggle(this, '.filter-countries .overflow-filter')"]
    | Show all

app/views/search/_filter_owners.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.filter-section-title
  | OWNER
- @owners ||= []
- @render_owners = SearchFilterDecorator.new(@owners) { |t| @selected_owner.include?(t.id) }
.filter-owners
  - @render_owners.renderables.each do |t|
    div class = t.html_class
      input.filter_checkbox[value=t.item.id id="owner_#{t.item.id}" name="owner[]" type="checkbox" onclick="$('#search_filter').submit();" checked=t.checked]
      = label_tag nil, "#{t.item.full_name} (#{@owners_count[t.item.id]})", for: "owner_#{t.item.id}"
- if @render_owners.show_more?
  a[onclick="filterOverflowToggle(this, '.filter-owners .overflow-filter')"]
    | Show all

app/views/search/_filter_subject_areas.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.filter-section-title
  | SUBJECT AREA
- @subject_areas ||= []
- @render_areas = SearchFilterDecorator.new(@subject_areas) { |t| @selected_subject_area.include?(t.id) }
.filter-subject-areas
  - @render_areas.renderables.each do |t|
    div class = t.html_class
      input.filter_checkbox[value=t.item.id id="subject_area_#{t.item.id}" name="subject_area[]" type="checkbox" onclick="$('#search_filter').submit();" checked=t.checked]
      = label_tag nil, "#{t.item.name} (#{@subject_areas_count[t.item.id]})", for: "subject_area_#{t.item.id}"
- if @render_areas.show_more?
  a[onclick="filterOverflowToggle(this, '.filter-subject-areas .overflow-filter')"]
    | Show all

app/views/search/_filter_tags.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.filter-section-title
  | TAG
- @tags ||= []
- @render_tags = SearchFilterDecorator.new(@tags) { |t| @selected_tags.include?(t.id) }
.filter-tags
  - @render_tags.renderables.each do |t|
    div class = t.html_class
      input.filter_checkbox[value=t.item.id id="tag_#{t.item.id}" name="tags[]" type="checkbox" onclick="$('#search_filter').submit();" checked=t.checked]
      = label_tag nil, "#{t.item.name} (#{@tags_count[t.item.id]})", for: "tag_#{t.item.id}"
- if @render_tags.show_more?
  a[onclick="filterOverflowToggle(this, '.filter-tags .overflow-filter')"]
    | Show all

app/views/search/_searchbar.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.searchbar
  .searchbar__container
    label.searchbar__label[for="form_searchbar"]
      | Search Datasets
    = form_tag(search_path, method: :get, id: "form_searchbar", class: "input-group input-group-lg") do
      input.form-control.searchbar__input[id="searchbar_input" name="query" type="text" value=@query placeholder="Enter search query" autocomplete="off"]
      span.input-group-btn
        button.btn.btn-default.searchbar__btn[name="commit" type="submit"]
          | GO
    - if @search_duration && @total_results
      p.searchbar__summary
        = @total_results
        |  results in
        = " #{@search_duration} ms"
javascript:
	$("#searchbar_input").autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/search/autocomplete",
          dataType: "json",
          data: {
            q: request.term
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 1
    });

app/views/search/_subnavigation.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
.subnavigation
  span
    i.icon.icon-search-results-icon
    - link_text = "SEARCH RESULTS (#{@total_results})" if @total_results
    = link_to link_text || 'SEARCH RESULTS', search_url(query: @query)
  span
    i.icon.icon-related-terms-icon
    = link_to "RELATED TAGS", search_related_tags_url(query: @query)
  span
    i.icon.icon-related-people-icon
    = link_to "RELATED PEOPLE", search_related_people_url(query: @query)

app/views/search/related_people.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
= render "subnavigation"
#tag-cloud
javascript:
  (function(){
    var tags = #{raw(@tags.to_json)};
    TagCloud.load(tags, 600, 500);
  })();

app/views/search/related_tags.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
= render "subnavigation"
#tag-cloud
javascript:
  (function(){
    var tags = #{raw(@tags.to_json)};
    TagCloud.load(tags, 600, 500);
  })();

app/views/search/search.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
- if @datasets.present?
  .row.content-container
    .col-md-4.filter-container
      .title
        | Refine by
      form#search_filter
        input type="hidden" name="query" value=@query
        = render 'filter_countries'
        = render 'filter_subject_areas'
        = render 'filter_tags'
        = render 'filter_owners'

        button.btn.btn-primary.clear-filter[onclick="clear_filters()" type="button"]
          | CLEAR FILTERS

    .col-md-8.results-container
      - @datasets.each_with_hit do |d, hit|
        div

        .row.dataset-result-row
          .col-md-12.dataset-result-column
            .row.header
              .col-md-9.result-title
                i.icon.icon-dataset-icon-1
                = link_to d.name, dataset_path(d)
              .col-md-3.created-at.pull-right.text-right
                = formatted_date(d.created_at)
            .row.sub-header
              .col-md-12.text-right.actions
                span.subject-area
                  i.icon.icon-subject-area-icon
                  = link_to d.subject_area_name, search_path('subject_area[]' => d.subject_area_id)
                - if d.owner && d.owner.is_active
                  span.owner
                    i.icon.icon-pencil-icon
                    = link_to d.owner_full_name, search_path('owner[]' => d.owner_id)
                  img.profile-image[src= d.owner.image]
                - else
                  span.owner
                    i.icon.icon-pencil-icon
                    a#owner-help[href="#" data-toggle="tooltip" data-trigger="hover click" data-placement="top" title="Dataset owner does not exist in Linea. Please contact Admin support team to change dataset ownership."]
                      s
                        = d.owner_full_name
            .row.description
              .col-md-12
                - if hit.try(:[], :highlight).try(:[], :description)
                  p
                    = raw(hit[:highlight][:description].to_a.join('').truncate(510, separator: /\s/))
                    = link_to ' (read more)', dataset_path(d)
                - else
                  p
                    = raw(d.description.truncate(400))
                    = link_to ' (read more)', dataset_path(d)
            .row.tags
              .col-md-12
                - d.tags.each do |t|
                  = link_to(t.name, search_path(tags: [t.id]), class: "label label-default")
      .row.pagination-row
        .col-md-12
          = will_paginate @datasets, { previous_label: "PREVIOUS", next_label: "NEXT"}

  javascript:
    function clear_filters() {
      $("#form_searchbar").submit();
    }

    function disableClearFilterBtn () {
      var checkedFilter = $('.filter_checkbox[checked]');
      var clearFilterBtn = $('.clear-filter');
      if( checkedFilter.length === 0 ) {
        clearFilterBtn.attr('disabled','disabled');
      }
    }

    $(document).ready( function() {
      disableClearFilterBtn();
    });

    function filterOverflowToggle(element, overflow_class) {
      $(overflow_class).slideToggle();
      if( $(element).html() === "Show all" ) {
        $(element).html("Hide all");
      }else{
        $(element).html("Show all");
      }
    }

- else
  .row.content-container
    h2.center
      | No search results found