config/routes.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
require 'sidekiq/api'

Rails.application.routes.draw do
  namespace :admin do
    resources :terms_of_use, controller: :terms_of_use
    resources :users
    root to: "users#index"
  end

  root to: 'search#search'

  resources :request_accesses do
    member do
      post :approve
      post :reject
    end
  end

  resources :dataset_algorithms

  resources :update_activities


  # temporarily disabled by BDP-820
  get 'newsfeed' => 'newsfeed#index'
  get 'newsfeed/load_more'

  resources :datasources

  resources :like_activities

  resources :review_activities

  resources :share_activities

  resources :search_activities

  resources :view_activities

  resources :ingest_activities

  resources :contributors

  resources :columns

  resources :algorithms

  resources :user_elasticsearch_solutions

  get 'sessions/login', as: 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  get 'auth/:provider/callback', to: 'sessions#create'
  #post 'sessions/login_attempt'
  get 'sessions/impersonate'
  get 'sessions/cancel_impersonation'

  resources :dataset_visual_tools

  resources :tags do
    collection do
      get :autocomplete
      get :popular
    end
  end

  resources :lineages do
    member do
      get :details
    end
  end

  resource :terms_of_use, controller: :terms_of_use, only: [:create] do
    member do
      get :accept
      get :actual
    end
  end

  resource :tables do
    resources :columns
  end

  resources :datasets, only: :show do
    # resources :transformations
    resources :attributes, controller: :dataset_attributes, except: [:index, :show], as: :dataset_attributes do
      collection do
        get :autocomplete
      end
    end

    resources :notes, only: [:edit, :create, :update, :destroy]

    resource :tables do
      resources :columns
    end

    member do
      get :like
      get :share
      get :explore_lineage
      get :lineage_dataset_details

      post :update_columns
      post :update_tags
      post :upload_metadata
      get :redisplay_columns

      post 'ask-for-request' => 'dataset/request_accesses#create'
      get 'connection_info' => 'dataset/connection_info#show',
          as: :connection_info

      namespace :dataset, path: '' do
        resources :request_accesses, only: [:index], param: :request_access_id do
          member do
            post :approve
            post :reject
          end
        end
      end
    end
  end

  resources :terms_of_services

  resources :subject_areas

  get 'search/search'
  get 'search/related_tags'
  get 'search/related_people'
  get 'search' => 'search#search', as: :search
  get 'search/autocomplete'

  get 'mydatasets' => 'users#mydatasets', as: :mydatasets

  resources :users

  resources :my_datasets, only: [:new, :create, :edit, :update, :destroy] do
    resource :transformation, only:  [:create, :edit, :update]
    member do
      get :check_on_status
      get :template_for_initial_scenario
    end
  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      post 'sessions' => 'sessions#create'
      jsonapi_resources :datasets
      jsonapi_resources :dataset_attributes
      jsonapi_resources :notes
      jsonapi_resources :tags
      jsonapi_resources :subject_areas
      jsonapi_resources :datasources
      jsonapi_resources :users do
        collection do
          post :verify
        end
      end
    end
  end

  # sidekiq
  mount Sidekiq::Web, :at => 'sidekiq', :constraints => SidekiqWebConstraint.new
  get "sidekiq/status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new.size < 10000 ? "OK" : "UHOH"]] }

  match '*path' => 'application#routing_error', via: :all
 # get ':controller/:action'
end

app/models/tag.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
class Tag < ActiveRecord::Base
  default_scope { order(:name) }

  has_many :dataset_tags
  has_many :datasets, through: :dataset_tags

  belongs_to :created_by, class_name: 'User'

  delegate :full_name, to: :created_by, prefix: true

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def self.proceed_tags(tag_ids)
    ids = []
    tag_ids.reject(&:blank?).each do |t|
      if Tag.find_by_id(t)
        ids << t
        next
      end
      created_tag = Tag.find_or_create_by(name: t)
      ids << created_tag.id if created_tag.valid?
    end
    ids
  end

  def name
    attributes['name'].downcase if attributes['name']
  end
end

app/controllers/api/v1/tags_controller.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
module Api
  module V1
    class TagsController < RestrictedApiController
      before_action :bad_request, only: [:update, :destroy]
    end
  end
end

app/controllers/tags_controller.rb
# Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
class TagsController < ApplicationController
  before_filter :authenticate_admin, except: [:autocomplete, :popular]
  respond_to :html, :xml, :json

  def index
    @tags = Tag.all
  end

  def show
    @tag = tag
    @lineages = {}
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = tag
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save!
    respond_with @tag
  end

  def update
    tag.update!(tag_params)
    respond_with tag
  end

  def destroy
    tag.destroy!
    respond_with tag
  end

  def autocomplete
    render json: fetch_suggestions, root: false
  end

  def popular
    tags = DatasetTag.joins(:tag).select('tag_id, tags.name as text, count(dataset_tags.id) as size')
           .group('tag_id, text').order('size DESC').limit(20)
    render json: tags, root: false
  end

  private

  def fetch_suggestions
    SearchService.autocomplete(
      query: params.fetch('q', ''),
      fields: ['tag']
    )
  end

  def tag
    @tag ||= Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name, :created_by_id)
  end
end

app/views/tags/_form.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #error_explanation
      h2
        = pluralize(@tag.errors.count, "error")
        |  prohibited this tag from being saved:
      ul
        - @tag.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :created_by
    br
    = f.collection_select :created_by_id, User.all, :id, :full_name
  .actions
    = f.submit

app/views/tags/edit.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
h1
  | Editing tag
= render 'form'
= link_to 'Show', @tag
|  |
= link_to 'Back', tags_path

app/views/tags/index.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
h1
  | Listing tags
table.table
  thead
    tr
      th
        | Name
      th
        | Created by
      th[colspan="3"]
  tbody
    - @tags.each do |tag|
      tr
        td
          = tag.name
        td
          = tag.created_by_full_name if tag.created_by
        td
          = link_to 'Show', tag
        td
          = link_to 'Edit', edit_tag_path(tag)
        td
          = link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
h1
  | New tag
= render 'form'
= link_to 'Back', tags_path

app/views/tags/show.html.slim
/Copyright© 2017 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.  Licensed under the Apache License, Version 2.0 (the "License");    you may not use this file except in compliance with the License.    You may obtain a copy of the License at       http://www.apache.org/licenses/LICENSE-2.0     Unless required by applicable law or agreed to in writing, software    distributed under the License is distributed on an "AS IS" BASIS,    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    See the License for the specific language governing permissions and    limitations under the License. 
p#notice
  = notice
p
  strong
    | Name:
  = @tag.name
p
  strong
    | Created by:
  = @tag.created_by_full_name if @tag.created_by

= link_to 'Edit', edit_tag_path(@tag)
|  |
= link_to 'Back', tags_path